# Generated by Django 5.1.7 on 2025-05-03 04:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smartphone', '0002_alter_manufacturers_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='smartphone',
            name='release_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
