# Generated by Django 5.1.7 on 2025-04-20 19:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Manufacturers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('country_origin', models.CharField(max_length=30)),
                ('date_of_fundation', models.DateField()),
                ('website', models.URLField()),
            ],
        ),
        migrations.CreateModel(
            name='Smartphone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('ram', models.IntegerField()),
                ('storage', models.IntegerField()),
                ('screen_size', models.CharField(max_length=30)),
                ('manufacturers', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='smartphone.manufacturers')),
            ],
        ),
    ]
